version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lifemirror
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
    volumes:
      - minio-data:/data

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/lifemirror
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: lifemirror
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
      - minio

  worker:
    build: .
    command: celery -A src.workers.celery_app.celery worker -Q media -l info
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/lifemirror
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: lifemirror
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis
      - minio

volumes:
  db-data:
  minio-data:
